# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "nvme" "xhci_pci" "ahci" "thunderbolt" "usbhid" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/3e5658eb-f316-490b-855c-9efce6e920eb";
      fsType = "btrfs";
      options = [ "subvol=@root" ];
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/2A6B-F8F4";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  fileSystems."/home" =
    { device = "/dev/disk/by-uuid/3e5658eb-f316-490b-855c-9efce6e920eb";
      fsType = "btrfs";
      options = [ "subvol=@home" ];
      neededForBoot = true;
    };

  fileSystems."/nix" =
    { device = "/dev/disk/by-uuid/3e5658eb-f316-490b-855c-9efce6e920eb";
      fsType = "btrfs";
      options = [ "subvol=@nix" ];
    };

  fileSystems."/persist" =
    { device = "/dev/disk/by-uuid/3e5658eb-f316-490b-855c-9efce6e920eb";
      fsType = "btrfs";
      options = [ "subvol=@persist" ];
      neededForBoot = true;
    };

  fileSystems."/var/log" =
    { device = "/dev/disk/by-uuid/3e5658eb-f316-490b-855c-9efce6e920eb";
      fsType = "btrfs";
      options = [ "subvol=@log" ];
    };

#  ---  DATA DRIVES AND MOUNTING POINTS

  fileSystems."/mnt/windows" = {
    device = "/dev/disk/by-uuid/B4A894D9A8949B84";
    fsType = "ntfs";
    options = [ "rw" "uid=1000" "gid=100" "dmask=022" "fmask=133" "nofail" ];
  };

  fileSystems."/mnt/hp-ssd" = {
    device = "/dev/disk/by-uuid/C64A6A6B4A6A57E7";
    fsType = "ntfs3";
    options = [ "rw" "uid=1000" "gid=100" "dmask=022" "fmask=133" "nofail" ];
  };

  fileSystems."/mnt/data" = {
    device = "/dev/disk/by-uuid/ACF89E50F89E18A2";
    fsType = "ntfs3";
    options = [ "rw" "uid=1000" "gid=100" "dmask=022" "fmask=133" "nofail" ];
  };

  fileSystems."/mnt/sda" = {
    device = "/dev/disk/by-uuid/903A9B663A9B485C";
    fsType = "ntfs3";
    options = [ "rw" "uid=1000" "gid=100" "dmask=022" "fmask=133" "nofail" ];
  };

  swapDevices = [ ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
